name: Lint Code
description: Lint code using GitHub Super Linter with selective validation

inputs:
  module_path:
    description: "Path to the module in feature branch"
    required: true
  github_token:
    description: "GitHub token for authentication"
    required: true
  validate_markdown:
    description: "Toggle markdown validation based on input"
    required: false
    default: "true"
  validate_all_codebase:
    description: "Toggle codebase validation based on input"
    required: false
    default: "true"
  disable_all_linters:
    description: "Toggle linter validation based on input"
    required: false
    default: "false"
  validate_github_actions:
    description: "Toggle github actions validation based on input"
    required: false
    default: "true"
  MARKDOWNLINT_CONFIG_FILE:
    description: "Path to custom markdownlint configuration file"
    required: false
    default: "./.markdownlint.json"
  node_version:
    description: "Node.js version for linting setup"
    required: false
    default: "20"
  disable_linters:
    description: "Comma-separated list of linters to disable"
    required: false
    default: "ARM,NATURAL_LANGUAGE" # Default linters to disable

runs:
  using: "composite"
  steps:
    - name: Set dynamic path for linting
      shell: bash
      run: |
        MODULE_PATH="${{ inputs.module_path }}"
        echo "Module path for linting: $MODULE_PATH"

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}

    - name: Lint Codebase with Super Linter
      uses: github/super-linter@v5
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        VALIDATE_ALL_CODEBASE: ${{ inputs.validate_all_codebase }}
        DISABLE_ALL_LINTERS: ${{ inputs.disable_all_linters }}
        DISABLE_LINTERS: ${{ inputs.disable_linters }}
        VALIDATE_MARKDOWN: ${{ inputs.validate_markdown }}
        VALIDATE_GITHUB_ACTIONS: ${{ inputs.validate_github_actions }}
        MARKDOWNLINT_CONFIG_FILE: ${{ inputs.MARKDOWNLINT_CONFIG_FILE }}
